/// Queries are explicitly allowlisted. New operations default to transactional
/// commands until their lack of side effects has been reviewed.
bool isDatabaseQuery(String domain, String method) => switch (domain) {
      'build' => const {
          'get',
          'listRecoverable',
          'listHistory',
          'validateScope',
          'manifestItemCount',
          'hasDirectoryFrontier',
          'nextDirectory',
          'listManifestPage',
          'hasPendingEntityPreviewWork',
          'hasPendingNodePreviewWork',
          'hasPendingDocumentPreviewWork',
        }.contains(method),
      'library' => const {
          'listAudioPlaybackSessions',
          'getAudioPlaybackSession',
          'getEntityByPath',
          'getEntitiesByPaths',
          'getEntitiesByIds',
          'hasEntityForPath',
          'listRecentOpenedEntities',
          'listRecentlyModifiedEntities',
          'entityIdsUnderDirectorySource',
          'directoryIndexRootIdsOverlapping',
          'directoryIndexRootForSource',
          'isDirectoryIndexRootEmpty',
          'inspectDirectoryIndexDeletion',
          'directoryNodeRelativePath',
          'listOutgoingEdges',
          'listIncomingEdges',
          'listGraphEdges',
          'listGraphNodes',
          'listGraphNodePositions',
          'listIndexRoots',
          'listChildNodes',
          'getIndexNode',
          'directoryIndexRootForNode',
          'listNodePath',
          'listIndexNodeSummaries',
          'listIndexTree',
          'loadIndexTree',
          'listEntitiesUnderNode',
          'listEntitiesDirectlyUnderNode',
          'listEntityPageByTypes',
          'listEntitiesForNodeLinkPicker',
          'listEntityPageDirectlyUnderNode',
          'listEntityPageRecursivelyUnderNode',
          'willDeleteEntitiesWhenDeletingNode',
          'countEntitiesUnderIndexNode',
          'countEntitiesUnderIndexNodes',
          'getEntity',
          'listIndexNodeIdsForEntity',
          'listIndexNodePreviews',
          'listDirtyPreviewRoots',
          'nodePreviewAssetPath',
          'owningIndexRootForNode',
          'listIndexNodeAncestors',
          'listIndexNodeDescendantIds',
          'listNodePreviewCandidates',
          'getNodePreviewOverride',
        }.contains(method),
      _ => false,
    };

/// Filesystem garbage collection and WAL checkpoints cannot be rolled back.
bool isDatabaseMaintenance(String domain, String method) =>
    (domain == 'library' && method == 'collectRetiredPreviewAssets') ||
    (domain == 'build' && method == 'checkpoint');
