import 'dart:io';
import 'package:analyzer/dart/ast/ast.dart';
import 'package:analyzer/dart/analysis/utilities.dart';
import 'package:path/path.dart' as p;

// Transitional API generation: transport code is mechanical; domain rules
// remain in repositories. Run from this tool directory after interface edits.
void main() {
  final root = p.normalize(p.join(Directory.current.path, '../..'));
  final directory = Directory(p.join(root, 'lib/src/core/database'));
  for (final build in [false, true]) {
    final methods = <String, MethodDeclaration>{};
    for (final file in directory.listSync().whereType<File>()) {
      final name = p.basename(file.path);
      if (build ? name != 'library_build_repository.dart'
          : (!name.endsWith('_repository.dart') && name != 'library_repository_base.dart' && name != 'index_build_mixin.dart') || name == 'library_build_repository.dart') {
        continue;
      }
      final unit = parseString(content: file.readAsStringSync(), throwIfDiagnostics: false).unit;
      for (final declaration in unit.declarations) {
        final members = switch (declaration) {
          ClassDeclaration d => d.body is BlockClassBody ? (d.body as BlockClassBody).members : <ClassMember>[],
          MixinDeclaration d => d.body.members,
          _ => <ClassMember>[],
        };
        for (final member in members.whereType<MethodDeclaration>()) {
          final method = member.name.lexeme;
          if (method.startsWith('_') || member.isGetter || member.isSetter || member.isStatic ||
              member.typeParameters != null || member.parameters == null ||
              member.parameters!.toSource().contains('Function(')) {
            continue;
          }
          methods[method] = member;
        }
      }
    }
    final base = build ? 'Build' : 'Library';
    final kind = build ? 'build' : 'library';
    final access = StringBuffer("// Generated by tools/module_codegen/generate.dart.\nimport 'dart:async';\nimport '../../core/domain/models.dart';\n");
    if (!build) access.writeln("import '../../core/thumbnails/thumbnail_store.dart';");
    access.writeln('abstract interface class ${base}Access {');
    if (!build) access.writeln('String get storageDirectoryPath; ThumbnailStore get thumbnailStore;');
    final client = StringBuffer("// Generated by tools/module_codegen/generate.dart.\nimport '../../core/domain/models.dart';\nimport '../infrastructure/database_host.dart';\nimport '${kind}_access.dart';\n");
    if (!build) client.writeln("import '../../core/thumbnails/thumbnail_store.dart';");
    client.writeln('class ${base}Client implements ${base}Access {');
    client.writeln('${base}Client(this.host); final DatabaseHost host;');
    if (!build) client.writeln('@override String get storageDirectoryPath => host.storageDirectoryPath; @override ThumbnailStore get thumbnailStore => ThumbnailStore(storageDirectoryPath);');
    final dispatch = StringBuffer("// Generated by tools/module_codegen/generate.dart.\nimport '../../core/domain/models.dart';\nimport '../../core/database/${build ? 'library_build_repository' : 'library_repository'}.dart';\n");
    dispatch.writeln('Future<Object?> dispatch$base(${build ? 'LibraryBuildRepository' : 'LibraryRepository'} repository, String method, Map<String, Object?> args) async { switch(method) {');
    for (final e in methods.entries) {
      final m = e.value;
      var result = m.returnType?.toSource() ?? 'dynamic';
      final isFuture = result.startsWith('Future<');
      if (isFuture) result = result.substring(7, result.length - 1);
      final params = m.parameters!.toSource();
      access.writeln('FutureOr<$result> ${e.key}$params;');
      final map = <String>[];
      final call = <String>[];
      for (final parameter in m.parameters!.parameters) {
        final normal = parameter is DefaultFormalParameter ? parameter.parameter : parameter;
        final name = normal.name!.lexeme;
        final type = normal is SimpleFormalParameter ? normal.type?.toSource() ?? 'dynamic' : 'dynamic';
        final defaultValue = parameter is DefaultFormalParameter ? parameter.defaultValue?.toSource() : null;
        final cast = defaultValue == null
            ? "args['$name'] as $type"
            : "(args['$name'] as ${type.endsWith('?') ? type : '$type?'}) ?? $defaultValue";
        final materialized = type.startsWith('Iterable<') ? '$name${type.endsWith('?') ? '?' : ''}.toList(growable: false)' : name;
        map.add("'$name': $materialized");
        call.add('${parameter.isNamed ? '$name: ' : ''}$cast');
      }
      client.writeln('@override Future<$result> ${e.key}$params async {');
      client.writeln("${result == 'void' ? '' : 'return ('}await host.call('$kind', '${e.key}', {${map.join(',')}})${result == 'void' ? ';' : ') as $result;'} }");
      dispatch.writeln("case '${e.key}': ${result == 'void' ? '' : 'return '}${isFuture ? 'await ' : ''}repository.${e.key}(${call.join(',')});${result == 'void' ? ' return null;' : ''}");
    }
    access.writeln('}'); client.writeln('}');
    dispatch.writeln("default: throw ArgumentError.value(method, 'method', 'Unknown $kind operation'); } }");
    final target = Directory(p.join(root, 'lib/src/modules', kind))..createSync(recursive: true);
    File(p.join(target.path, '${kind}_access.dart')).writeAsStringSync(access.toString());
    File(p.join(target.path, '${kind}_client.dart')).writeAsStringSync(client.toString());
    File(p.join(target.path, '${kind}_dispatch.dart')).writeAsStringSync(dispatch.toString());
    stdout.writeln('$base: ${methods.length} methods');
  }
}
